// Generated by https://quicktype.io

export interface IProduct {
  status:    number;
  message:   string;
  timestamp: string;
  data?:      data[];
}

export interface data {
  intro:              string;
  payment:            string;
  paymentInfo:        PaymentInfo[];
  specification:      string;
  guide:              string;
  vipRebateRate:      number;
  employeeRebateRate: number;
  sample_images:      string[];
  purchaseLimitInfo:  PurchaseLimitInfo;
  insurance:          boolean;
  store_name:         string;
  isKolProduct:       boolean;
  partial_price:      number;
  redeem_all:         number;
  redeem_partial:     number;
  restricted:         boolean;
  redeem:             boolean;
  pre_order_type:     string;
  pre_order_info:     string;
  onShelf:            boolean;
  soldout:            boolean;
  mid:                number;
  bottomCid:          number;
  productStatus:      ProductStatus;
  isHiddenCid:        boolean;
  isValidCid:         boolean;
  sid:                number;
  cid:                number;
  pid:                number;
  shelfId:            number;
  category_name:      string;
  name:               string;
  price:              string;
  list_price:         number;
  special_price:      number;
  real_price:         number;
  special:            boolean;
  discount:           boolean;
  allowance:          boolean;
  disable:            boolean;
  delivery:           string;
  transport_code:     string;
  combined:           boolean;
  measure:            Measure[];
  description:        string;
  payMethodList:      string[];
  storeLogoType:      string;
  checkout_type:      number;
  allowance_discount: number;
  cart_type:          number;
  isShowUpdateButton: boolean;
  tags:               Tag[];
  startSaleTime:      string;
  deliveryInfos:      DeliveryInfo[];
  specInfo:           Measure[];
  flags:              string[];
  productLimit:       number;
  afterDiscountPrice: number;
  noticeMsg:          string;
  showSaleMsg:        boolean;
}

export interface DeliveryInfo {
  deliveryType: string;
  cartTypeId:   number;
  deliveryName: string;
}

export interface Measure {
  groupTitle:         string;
  groupName:          string;
  id:                 number;
  qty:                number;
  purchase_qty:       number;
  purchase_min_qty:   number;
  sold_out:           boolean;
  safe_inventory_qty: number;
  group1:             string;
  groupName1:         string;
}

export interface PaymentInfo {
  period:               number;
  payType:              string;
  isHighestInstallment: boolean;
  payTypeObject:        string;
}

export interface ProductStatus {
  id:   number;
  name: string;
}

export interface PurchaseLimitInfo {
  showMessage:    string;
  redirectUrl:    string;
  redirectText:   string;
  locationChange: boolean;
  isValidate:     boolean;
}

export interface Tag {
  id:              number;
  name:            string;
  borderColor:     string;
  backgroundColor: string;
  textColor:       string;
}
